apiVersion: v1
kind: Namespace
metadata:
  name: personal-scripts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: overtime-service-account
  namespace: personal-scripts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: overtime-role
  namespace: personal-scripts
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: overtime-rolebinding
  namespace: personal-scripts
subjects:
  - kind: ServiceAccount
    name: overtime-service-account
    namespace: personal-scripts
roleRef:
  kind: Role
  name: overtime-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: overtime-automation
  namespace: personal-scripts
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: overtime-service-account
          containers:
            - name: overtime-automation
              image: matesousa/overtime-script:v7
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: SENDER_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: email-secrets
                      key: SENDER_EMAIL
                - name: RECIPIENT_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: email-secrets
                      key: RECIPIENT_EMAIL
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: email-secrets
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: email-secrets
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: email-secrets
                      key: AWS_REGION
                - name: TESTING
                  value: "true"
          restartPolicy: OnFailure
