apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overtime-automation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MateSousa/overtime-script.git
    targetRevision: HEAD
    path: k8s
    directory:
      include: "manifests.yaml"
      exclude: "argocd/*"
  destination:
    server: https://kubernetes.default.svc
    namespace: personal-scripts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
