name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version tag
        id: tag
        run: echo "tag=v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: matesousa/overtime-script:latest,matesousa/overtime-script:${{ steps.tag.outputs.tag }}
          cache-from: type=registry,ref=matesousa/overtime-script:buildcache
          cache-to: type=registry,ref=matesousa/overtime-script:buildcache,mode=max

      - name: Update K8s manifest
        run: |
          sed -i "s|image: matesousa/overtime-script:.*|image: matesousa/overtime-script:${{ steps.tag.outputs.tag }}|" k8s/manifests.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update image tag to ${{ steps.tag.outputs.tag }}"
          file_pattern: 'k8s/manifests.yaml'

